units:
  kx: cx
  ky: cy

  pd: 2
  px: kx + pd
  py: ky + pd

  wpd: 2.5
  short_wpd: 0.5
  inner_wpd: -0.4

  # M2 screws
  screwsize: 1.5
  standoffsize: 2.5

  choc: 13.8

points:
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [150, -150]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          key:
            splay: 15
          rows:
            bottom:
                column_net: P18
            home:
                column_net: P15
            top:
                column_net: P14
        ring:
          key:
            stagger: 14
            splay: -10
            origin: [0, -ky]
          rows:
            bottom:
                column_net: P16
            home:
                column_net: P10
            top:
                column_net: P9
        middle:
          key:
            stagger: 4
            splay: -3.5
            origin: [0, -ky]
          rows:
            bottom:
                column_net: P8
            home:
                column_net: P7
            top:
                column_net: P6
        index:
          key:
            stagger: -15
            splay: -8
            origin: [0, -ky]
          rows:
            bottom:
                column_net: P5
            home:
                column_net: P4
            top:
                column_net: P3
        inner:
          key:
            stagger: -3
          rows:
            bottom:
                column_net: P2
            home:
                column_net: P0
            top:
                column_net: P1
      rows:
        bottom:
        home:
        top:
    thumbs:
      key: 
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_index_bottom
        shift: [kx/4,-25]
      columns:
        inner:
          key:
            splay: -5
            shift: [-2,2]
            column_net: P19
        center:
          key:
            splay: -8
            column_net: P20
        outer:
          key:
            width: 1.25kx
            splay: -13
            origin: [-9, -9.5]
            rotate: 90
            column_net: P21
      rows:
        cluster:
outlines:
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5, ky-0.5]
  switches:
    - what: rectangle
      where: true
      bound: false
      size: [choc, choc]

  cutout_circle_thumb:
    - what: circle
      radius: 200
      where:
        ref: thumbs_inner_cluster
        shift: [-16, -211]
  cutout_circle_thumb_wall:
    - what: circle
      radius: 200-wpd
      where:
        ref: thumbs_inner_cluster
        shift: [-16, -211]
  cutout_circle_thumb_inner_wall:
    - what: circle
      radius: 200-short_wpd
      where:
        ref: thumbs_inner_cluster
        shift: [-16, -211]
  cutout_circle_thumb_inner_inner_wall:
    - what: circle
      radius: 200-inner_wpd
      where:
        ref: thumbs_inner_cluster
        shift: [-16, -211]

  cutout_circle_right:
    - what: circle
      radius: 250
      where:
        ref: matrix_inner_bottom
        shift: [281, 27]
  cutout_circle_right_wall:
    - what: circle
      radius: 250-wpd
      where:
        ref: matrix_inner_bottom
        shift: [281, 27]
  cutout_circle_right_inner_wall:
    - what: circle
      radius: 250-short_wpd
      where:
        ref: matrix_inner_bottom
        shift: [281, 27]
  cutout_circle_right_inner_inner_wall:
    - what: circle
      radius: 250-inner_wpd
      where:
        ref: matrix_inner_bottom
        shift: [281, 27]

  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px, -0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.5px, -0.75py]
          #shift: [-1px, -0.585py]
        - ref: thumbs_outer_cluster
          shift: [-0.52px, -0.5py]
        - ref: thumbs_outer_cluster
          shift: [0.5px, -0.51py]
        - ref: thumbs_outer_cluster
          shift: [2px, 0.35py]

        - ref: matrix_inner_top
          affect: r
        - shift: [-0.2px, 0.84py]

        - ref: matrix_inner_top
          shift: [0.5px, -0.5py]
        - ref: matrix_inner_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [-0.395px, 0.5py]

        - ref: matrix_index_top
          shift: [0.5px, 0.5py] 
        - ref: matrix_index_top
          shift: [-0.83px, 0.5py] 

        - ref: matrix_middle_top
          shift: [0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]

        - ref: matrix_ring_top
          shift: [0.57px, 0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        
        - ref: matrix_pinky_top
          shift: [0.8px, 0.5py]
      fillet: 1
  _case_board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px-short_wpd, 0.5py+short_wpd]
        - ref: matrix_pinky_bottom
          shift: [-0.5px-short_wpd, -0.5py-short_wpd]
        - ref: thumbs_inner_cluster
          shift: [-0.5px-short_wpd, -0.75py-short_wpd]
        - ref: thumbs_outer_cluster
          shift: [-0.52px-short_wpd, -0.5py-short_wpd]
        - ref: thumbs_outer_cluster
          shift: [0.5px+short_wpd, -0.51py-short_wpd]
        - ref: thumbs_outer_cluster
          shift: [2px+short_wpd, 0.35py+short_wpd]

        - ref: matrix_inner_top
          affect: r
        - shift: [0, 0.82py]

        - ref: matrix_inner_top
          shift: [0.5px+0.7, -0.5py+short_wpd]
        - ref: matrix_inner_top
          shift: [0.5px+short_wpd, 0.5py+short_wpd]
        - ref: matrix_inner_top
          shift: [-0.395px+short_wpd, 0.5py+short_wpd]

        - ref: matrix_index_top
          shift: [0.5px+short_wpd, 0.5py+short_wpd] 
        - ref: matrix_index_top
          shift: [-0.83px+short_wpd, 0.5py+short_wpd] 

        - ref: matrix_middle_top
          shift: [0.5px+short_wpd, 0.5py+short_wpd]
        - ref: matrix_middle_top
          shift: [-0.5px-short_wpd, 0.5py+short_wpd]

        - ref: matrix_ring_top
          shift: [0.57px-short_wpd, 0.5py+short_wpd]
        - ref: matrix_ring_top
          shift: [-0.5px-short_wpd, 0.5py+short_wpd]
        
        - ref: matrix_pinky_top
          shift: [0.8px-short_wpd, 0.5py+short_wpd]
      fillet: 1
  _case_inner_board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px-inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_pinky_bottom
          shift: [-0.5px-inner_wpd, -0.5py-inner_wpd]
        - ref: thumbs_inner_cluster
          shift: [-0.5px-inner_wpd, -0.75py-inner_wpd]
        - ref: thumbs_outer_cluster
          shift: [-0.52px-inner_wpd, -0.5py-inner_wpd]
        - ref: thumbs_outer_cluster
          shift: [0.5px+inner_wpd, -0.51py-inner_wpd]
        - ref: thumbs_outer_cluster
          shift: [2px+inner_wpd, 0.35py+inner_wpd]

        - ref: matrix_inner_top
          affect: r
        - shift: [0, 0.83py]

        - ref: matrix_inner_top
          shift: [0.5px-0.2, -0.5py+inner_wpd]
        - ref: matrix_inner_top
          shift: [0.5px+inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_inner_top
          shift: [-0.395px+inner_wpd, 0.5py+inner_wpd]

        - ref: matrix_index_top
          shift: [0.5px+inner_wpd, 0.5py+inner_wpd] 
        - ref: matrix_index_top
          shift: [-0.83px+inner_wpd, 0.5py+inner_wpd] 

        - ref: matrix_middle_top
          shift: [0.5px+inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_middle_top
          shift: [-0.5px-inner_wpd, 0.5py+inner_wpd]

        - ref: matrix_ring_top
          shift: [0.57px-inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_ring_top
          shift: [-0.5px-inner_wpd, 0.5py+inner_wpd]
        
        - ref: matrix_pinky_top
          shift: [0.8px-inner_wpd, 0.5py+inner_wpd]
      fillet: 1
  _case_xlboard:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px-wpd, 0.5py+wpd]
        - ref: matrix_pinky_bottom
          shift: [-0.5px-wpd, -0.5py-wpd]
        - ref: thumbs_inner_cluster
          shift: [-0.5px-wpd, -0.75py-wpd]
        - ref: thumbs_outer_cluster
          shift: [-0.52px-wpd, -0.5py-wpd]
        - ref: thumbs_outer_cluster
          shift: [0.5px+wpd, -0.51py-wpd]
        - ref: thumbs_outer_cluster
          shift: [2px+wpd, 0.35py+wpd]

        - ref: matrix_inner_top
          affect: r
        - shift: [0, 0.78py]

        - ref: matrix_inner_top
          shift: [0.5px+2.6, -0.5py+wpd]
        - ref: matrix_inner_top
          shift: [0.5px+wpd, 0.5py+wpd]
        - ref: matrix_inner_top
          shift: [-0.395px+wpd, 0.5py+wpd]

        - ref: matrix_index_top
          shift: [0.5px+wpd, 0.5py+wpd] 
        - ref: matrix_index_top
          shift: [-0.83px+wpd, 0.5py+wpd] 

        - ref: matrix_middle_top
          shift: [0.5px+wpd, 0.5py+wpd]
        - ref: matrix_middle_top
          shift: [-0.5px-wpd, 0.5py+wpd]

        - ref: matrix_ring_top
          shift: [0.57px-wpd, 0.5py+wpd]
        - ref: matrix_ring_top
          shift: [-0.5px-wpd, 0.5py+wpd]
        
        - ref: matrix_pinky_top
          shift: [0.8px-wpd, 0.5py+wpd]
      fillet: 1

  _mcucutout: 
    - what: rectangle
      size: [30,40]
      corner: 1
      where: matrix_inner_bottom
      adjust:
        shift: [px+5,0.35py]
  _mcucutout_edge: 
    - what: polygon
      #where: matrix_inner_bottom
      #adjust:
      #  shift: [px+5,0.35py]
      operation: stack
      points:
        - ref: thumbs_outer_cluster
          shift: [0.72px, 0.5py]
        - ref: thumbs_outer_cluster
          shift: [0.945px, -0.0py]
        - ref: thumbs_outer_cluster
          shift: [1px, -0.125py]
        - ref: thumbs_outer_cluster
          shift: [0.54px, -0.5py]

        - ref: thumbs_outer_cluster
          shift: [1.1px, -0.2py]
        - ref: thumbs_outer_cluster
          shift: [1.1px, -0.05py]
      fillet: 1

  _usbcutout:
    - what: rectangle
      size: [8,10]
      corner: 1
      where: matrix_inner_bottom
      adjust:
        shift: [1.1px-1.5, 1.19py]
  _ring_cutout_inner:
    - what: circle
      radius: 22
      where: matrix_index_top
      adjust: 
        shift: [-0.5px,-0.3py]
  _ring_cutout_outer:
    - what: circle
      radius: 28
      where: matrix_index_top
      adjust: 
        shift: [-0.5px,-0.3py]
  pcb: [
          +board,
          -cutout_circle_thumb,
          -cutout_circle_right
  ]
  _case_pcb: [
          +_case_board,
          -cutout_circle_right_inner_wall,
          -cutout_circle_thumb_inner_wall
  ]
  _case_inner_pcb: [
          +_case_inner_board,
          -cutout_circle_right_inner_inner_wall,
          -cutout_circle_thumb_inner_inner_wall
  ]

  plate: [
          +board,
          -cutout_circle_thumb,
          -cutout_circle_right,
          -_mcucutout,
          -_mcucutout_edge,
          -switches
  ]

  _case_xlplate: [
          +_case_xlboard,
          -cutout_circle_right_wall,
          -cutout_circle_thumb_wall
  ]

  _ring_cutout: [
          +_ring_cutout_outer,
          -_ring_cutout_inner
  ]

  mounting:
    - what: circle
      radius: screwsize
      where: matrix_pinky_top
      adjust: 
        shift: [0.62px,0.15py]
    - what: circle
      radius: screwsize
      where: matrix_pinky_bottom
      adjust: 
        shift: [0.4px,-0.65py]
    # - what: circle
    #   radius: screwsize
    #   where: matrix_inner_bottom
    #   adjust: 
    #     shift: [-0.6px,-0.45py]
    - what: circle
      radius: screwsize
      where: matrix_index_top
      adjust: 
        shift: [-0.635px,0.15py]
    - what: circle
      radius: screwsize
      where: thumbs_outer_cluster
      adjust: 
        shift: [0.6px,0py]
  standoff:  
    - what: circle
      radius: standoffsize
      where: matrix_pinky_top
      adjust: 
        shift: [0.62px,0.15py]
    - what: circle
      radius: standoffsize
      where: matrix_pinky_bottom
      adjust: 
        shift: [0.4px,-0.65py]
    # - what: circle
    #   radius: standoffsize
    #   where: matrix_inner_bottom
    #   adjust: 
    #     shift: [-0.6px,-0.45py]
    - what: circle
      radius: standoffsize
      where: matrix_index_top
      adjust: 
        shift: [-0.635px,0.15py]
    - what: circle
      radius: standoffsize
      where: thumbs_outer_cluster
      adjust: 
        shift: [0.6px,0py]

pcbs:
  Keiler:
    outlines:
      main:
        outline: pcb
    footprints:
      choc_hotswap:
        what: choc
        where: true
        adjust:
          rotate: 180
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: GND
      choc:
        what: choc
        where: true
        #adjust:
        #  rotate: 180
        params:
            keycaps: true
            reverse: false
            from: "{{column_net}}"
            to: GND
      mcu:
        what: promicro_pretty
        where: matrix_inner_bottom
        adjust:
          shift: [px,0.15py]
          rotate: -90
      pcm12:
        what: pcm12
        where: matrix_inner_bottom
        params:
          reverse: true
          from: pos
          to: RAW
        adjust:
          shift: [px, 1.19py]
          rotate: 180
      reset:
        what: b3u1000p
        where: matrix_inner_bottom
        params:
          r1: RST
          r2: GND
        adjust:
          shift: [1.4px, 1.1py]
          rotate: 90
      battPad:
        what: batterypad
        where: matrix_inner_bottom
        params:
          from: GND
        adjust:
          shift: [px, py]
          rotate: 90
      holeTopLeft:
        what: mountinghole
        where: matrix_pinky_top
        adjust: 
          shift: [0.62px,0.15py]
      holeBottomLeft:
        what: mountinghole
        where: matrix_pinky_bottom
        adjust: 
          shift: [0.4px,-0.65py]
      # holeCenter:
      #   what: mountinghole
      #   where: matrix_inner_bottom
      #   adjust: 
      #     shift: [-0.6px,-0.45py]
      holeTopRight:
        what: mountinghole
        where: matrix_index_top
        adjust: 
          shift: [-0.635px,0.15py]
      holeBottomRight:
        what: mountinghole
        where: thumbs_outer_cluster
        adjust: 
          shift: [0.6px,0py]
  platepcb:
    outlines:
      main:
        outline: plate
        layer: Edge.Cuts
    footprints:
      holeTopLeft:
        what: mountinghole
        where: matrix_pinky_top
        adjust: 
          shift: [0.62px,0.15py]
      holeBottomLeft:
        what: mountinghole
        where: matrix_pinky_bottom
        adjust: 
          shift: [0.4px,-0.65py]
      # holeCenter:
      #   what: mountinghole
      #   where: matrix_inner_bottom
      #   adjust: 
      #     shift: [-0.6px,-0.45py]
      holeTopRight:
        what: mountinghole
        where: matrix_index_top
        adjust: 
          shift: [-0.635px,0.15py]
      holeBottomRight:
        what: mountinghole
        where: thumbs_outer_cluster
        adjust: 
          shift: [0.6px,0py]
cases:
  _bottom:
    - name: _case_pcb
      extrude: 2
  _xlbottom:
    - name: _case_xlplate
      extrude: 2
  _outerWall:
    - name: _case_xlplate
      extrude: 9.2
  _innerWall:
    - name: _case_pcb
      extrude: 9.2
  _outerShelf:
    - name: _case_pcb
      extrude: 5
  _innerShelf:
    - name: _case_inner_pcb
      extrude: 5
  _wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _shelf:
    - what: case
      name: _outerShelf
      operation: add
    - what: case
      name: _innerShelf
      operation: subtract
  _holes:
    - name: mounting
      extrude: 5
  _standoffs:
    - name: standoff
      extrude: 5
  _usbcutout_case:
    - name: _usbcutout
      extrude: 12
      shift: [0,0,5]
  _ring_magnet:
    - name: _ring_cutout
      extrude: 0.6
      shift: [0,-1.5py,0.8]
  case:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: _xlbottom
      operation: add
    - what: case
      name: _wall
      operation: add
    - what: case
      name: _shelf
      operation: add
    - what: case
      name: _usbcutout_case
      operation: subtract
  _case_magnetic:
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
    - what: case
      name: _xlbottom
      operation: add
    - what: case
      name: _wall
      operation: add
    - what: case
      name: _shelf
      operation: add
    - what: case
      name: _usbcutout_case
      operation: subtract
    - what: case
      name: _ring_magnet
      operation: subtract
