units:
  kx: cx
  ky: cy

  pd: 2
  px: kx + pd
  py: ky + pd

  wpd: 2.5 #xlboard
  short_wpd: 0.5
  inner_wpd: -1.8 # pdb

  # M2 screws
  screwsize: 1.5
  standoffsize: 2.5

  choc: 13.8

points:
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [150, -150]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          key:
            splay: 3
          rows:
            bottom:
                column_net: P18
                rotate: 8
                shift: [3.3,5]
            home:
                column_net: P15
                rotate: 4
                shift: [-0.6,0.35]
            top:
                column_net: P14
                rotate: 4
                shift: [-0.6,0.35]
        ring:
          key:
            stagger: 10.5
            splay: -2
            origin: [0, -ky]
          rows:
            bottom:
                column_net: P16
                rotate: 7
                shift: [2,4]
            home:
                column_net: P10
                rotate: -5
                shift: [0.75,0.5]
            top:
                column_net: P9
                rotate: -5
                shift: [0.75,0.5]
        middle:
          key:
            stagger: 4
            splay: -7
            origin: [0, -ky]
          rows:
            bottom:
                column_net: P8
                rotate: 5
                shift: [0.5,4.6]
            home:
                column_net: P7
                rotate: 0
                shift: [0,0]
            top:
                column_net: P6
                rotate: 0
                shift: [0,0]
        index:
          key:
            stagger: 0
            splay: -6
            origin: [0, -ky]
          rows:
            bottom:
                column_net: P5
                rotate: 0
            home:
                column_net: P4
                rotate: 4
                shift: [-0.6,0.35]
            top:
                column_net: P3
                rotate: 4
                shift: [-0.6,0.35]
        inner:
          key:
            stagger: -9
          rows:
            bottom:
                column_net: P2
                rotate: -2
                shift: [-0.2,5]
            home:
                column_net: P0
                rotate: 4
                shift: [-0.6,0.35]
            top:
                column_net: P1
                rotate: 6
                shift: [-0.9,0.65]      
      rows:
        bottom:
        home:
        top:
    thumbs:
      key: 
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_index_bottom
        shift: [-8.5,-31.5]
      columns:
        inner:
          key:
            splay: 0
            rotate: 5
            shift: [-2.05,5.95]
            column_net: P19
        center:
          key:
            splay: -2
            rotate: -6
            shift: [-0.7,5.4]
            column_net: P20
        outer:
          key:
            splay: 1
            origin: [-67, 22]
            rotate: -20
            column_net: P21
      rows:
        cluster:

outlines:
  # Main board outline without padding
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.49px, 0.5py]
        - ref: matrix_pinky_top
          shift: [-0.49px, -0.45py]
        - ref: matrix_pinky_home
          shift: [-0.5px, -0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px, -0.5py]
        - ref: thumbs_inner_cluster
          shift: [-0.5px, -0.5py]
        - ref: thumbs_center_cluster
          shift: [-0.5px, -0.5py]
        - ref: thumbs_center_cluster
          shift: [0.45px, -0.5py]
        - ref: thumbs_outer_cluster
          shift: [0.5px, -0.5py]
        - shift: [0px, 1.15py]
        - shift: [0.35px, 0.3py]
        - shift: [0px, 0py]
        - ref: thumbs_outer_cluster
          shift: [0.195px, 2.92py]
        - ref: matrix_inner_top
          shift: [0.5px, -0.645py]
        - ref: matrix_inner_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [-0.395px, 0.5py]
        - ref: matrix_index_top
          shift: [0.5px, 0.5py]
        - ref: matrix_index_top
          shift: [-0.68px, 0.5py]
        - ref: matrix_middle_top
          shift: [0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_top
          shift: [0.565px, 0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_top
          shift: [0.9259px, 0.5py]
      fillet: 1

  # Case bottom outline with short_wpd padding
  case_board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.49px-short_wpd, 0.5py+short_wpd]
        - ref: matrix_pinky_top
          shift: [-0.49px-short_wpd, -0.45py-short_wpd]
        - ref: matrix_pinky_home
          shift: [-0.5px-short_wpd, -0.5py-short_wpd]
        - ref: matrix_pinky_bottom
          shift: [-0.5px-short_wpd, -0.5py-short_wpd]
        - ref: thumbs_inner_cluster
          shift: [-0.5px-short_wpd, -0.5py-short_wpd]
        - ref: thumbs_center_cluster
          shift: [-0.5px-short_wpd, -0.5py-short_wpd]
        - ref: thumbs_center_cluster
          shift: [0.45px+short_wpd, -0.5py-short_wpd]
        - ref: thumbs_outer_cluster
          shift: [0.5px+short_wpd*1, -0.5py-short_wpd]
        - shift: [0px, 1.15py+short_wpd]
        - shift: [0.35px, 0.3py]
        - shift: [0px, 0py]
        - ref: thumbs_outer_cluster
          shift: [0.195px+short_wpd*0.8, 2.92py+short_wpd]
        - ref: matrix_inner_top
          shift: [0.5px+short_wpd, -0.645py+short_wpd]
        - ref: matrix_inner_top
          shift: [0.5px+short_wpd, 0.5py+short_wpd]
        - ref: matrix_inner_top
          shift: [-0.34px-short_wpd, 0.5py+short_wpd]
        - ref: matrix_index_top
          shift: [0.5px+short_wpd, 0.5py+short_wpd]
        - ref: matrix_index_top
          shift: [-0.62px-short_wpd, 0.5py+short_wpd]
        - ref: matrix_middle_top
          shift: [0.5px+short_wpd, 0.5py+short_wpd]
        - ref: matrix_middle_top
          shift: [-0.5px-short_wpd, 0.5py+short_wpd]
        - ref: matrix_ring_top
          shift: [0.51px+short_wpd, 0.5py+short_wpd]
        - ref: matrix_ring_top
          shift: [-0.5px-short_wpd, 0.5py+short_wpd]
        - ref: matrix_pinky_top
          shift: [0.88px+short_wpd, 0.5py+short_wpd]
      fillet: 1

  # Outer case wall with wpd padding
  case_xlboard:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.49px-wpd, 0.5py+wpd]
        - ref: matrix_pinky_top
          shift: [-0.49px-wpd, -0.45py-wpd]
        - ref: matrix_pinky_home
          shift: [-0.5px-wpd, -0.5py-wpd]
        - ref: matrix_pinky_bottom
          shift: [-0.5px-wpd, -0.45py-wpd]
        - ref: thumbs_inner_cluster
          shift: [-0.4px-wpd, -0.5py-wpd]
        - ref: thumbs_center_cluster
          shift: [-0.4px-wpd, -0.5py-wpd]
        - ref: thumbs_center_cluster
          shift: [0.35px+wpd, -0.5py-wpd]
        - ref: thumbs_outer_cluster
          shift: [0.5px+wpd*0.9, -0.5py-wpd*0.9]
        - shift: [0px, 1.1py+wpd]
        - shift: [0.35px, 0.3py]
        - shift: [0px, 0py]
        - ref: thumbs_outer_cluster
          shift: [0.195px+wpd*0.5, 2.92py+wpd*1.05]
        - ref: matrix_inner_top
          shift: [0.5px+wpd, -0.645py+wpd*0.75]
        - ref: matrix_inner_top
          shift: [0.5px+wpd, 0.5py+wpd]
        - ref: matrix_inner_top
          shift: [-0.13px-wpd, 0.5py+wpd]
        - ref: matrix_index_top
          shift: [0.5px+wpd, 0.5py+wpd]
        - ref: matrix_index_top
          shift: [-0.43px-wpd, 0.5py+wpd]
        - ref: matrix_middle_top
          shift: [0.5px+wpd, 0.5py+wpd]
        - ref: matrix_middle_top
          shift: [-0.5px-wpd, 0.5py+wpd]
        - ref: matrix_ring_top
          shift: [0.31px+wpd, 0.5py+wpd]
        - ref: matrix_ring_top
          shift: [-0.5px-wpd, 0.5py+wpd]
        - ref: matrix_pinky_top
          shift: [0.72px+wpd, 0.5py+wpd]
      fillet: 1

  # Inner case using inner_wpd padding
  case_inner_pcb:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.49px-inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_pinky_top
          shift: [-0.49px-inner_wpd, -0.45py-inner_wpd]
        - ref: matrix_pinky_home
          shift: [-0.5px-inner_wpd, -0.5py-inner_wpd]
        - ref: matrix_pinky_bottom
          shift: [-0.5px-inner_wpd, -0.5py-inner_wpd]
        - ref: thumbs_inner_cluster
          shift: [-0.5px-inner_wpd, -0.5py-inner_wpd]
        - ref: thumbs_center_cluster
          shift: [-0.5px-inner_wpd, -0.5py-inner_wpd]
        - ref: thumbs_center_cluster
          shift: [0.45px+inner_wpd, -0.5py-inner_wpd]
        - ref: thumbs_outer_cluster
          shift: [0.5px+inner_wpd, -0.5py-inner_wpd]
        - shift: [0px, 1.15py+inner_wpd]
        - shift: [0.35px+inner_wpd, 0.3py+inner_wpd]
        - shift: [0px, 0py]
        - ref: thumbs_outer_cluster
          shift: [0.195px+inner_wpd, 2.92py+inner_wpd]
        - ref: matrix_inner_top
          shift: [0.5px+inner_wpd, -0.645py+inner_wpd]
        - ref: matrix_inner_top
          shift: [0.5px+inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_inner_top
          shift: [-0.42px-inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_index_top
          shift: [0.5px+inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_index_top
          shift: [-0.71px-inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_middle_top
          shift: [0.5px+inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_middle_top
          shift: [-0.5px-inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_ring_top
          shift: [0.56px-inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_ring_top
          shift: [-0.5px-inner_wpd, 0.5py+inner_wpd]
        - ref: matrix_pinky_top
          shift: [0.96px+inner_wpd, 0.5py+inner_wpd]
      fillet: 1
  
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5, ky-0.5]
  switches:
    - what: rectangle
      where: true
      bound: false
  mcu:
    - what: rectangle
      where: matrix_inner_bottom
      bound: false
      size: [1.75*kx, ky-0.5]
      adjust:
        shift: [1px,0.13py]
        rotate: -90
  combo:
    - name: board
    - operation: subtract
      name: keys
  board_1:
    - name: case_xlboard
    - operation: subtract
      name: case_board

pcbs:
  Keiler:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        adjust:
          rotate: 180
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: GND
      choc:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          from: "{{column_net}}"
          to: GND
      mcu:
        what: promicro_pretty
        where: matrix_inner_bottom
        adjust:
          shift: [1px,0.13py]
          rotate: -90
      pcm12:
        what: pcm12
        where: matrix_inner_bottom
        params:
          reverse: true
          from: pos
          to: RAW
        adjust:
          shift: [px, 1.19py]
          rotate: 180
      reset:
        what: b3u1000p
        where: matrix_inner_bottom
        params:
          r1: RST
          r2: GND
        adjust:
          shift: [1.4px, 1.1py]
          rotate: 90
      battPad:
        what: batterypad
        where: matrix_inner_bottom
        params:
          from: GND
        adjust:
          shift: [px, py]
          rotate: 90

  platepcb:
    outlines:
      main:
        outline: combo
        layer: Edge.Cuts

cases:
  _bottom:
    - name: case_board
      extrude: 1
  _xlbottom:
    - name: case_xlboard
      extrude: 1
  _outerWall:
    - name: case_xlboard
      extrude: 3.6
  _innerWall:
    - name: case_board
      extrude: 3.6
  _outerShelf:
    - name: case_board
      extrude: 2
  _innerShelf:
    - name: case_inner_pcb
      extrude: 2
  _wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _shelf:
    - what: case
      name: _outerShelf
      operation: add
    - what: case
      name: _innerShelf
      operation: subtract
  case:
    - what: case
      name: _bottom
      operation: add
    - what: case
      name: _wall
      operation: add
    - what: case
      name: _shelf
      operation: add
